### ISSUE TITLE
Server update Reborn Core to 1.11.2-2.16.1.114. causes Quantum Storage crash by: java.lang.NoClassDefFoundError: QuantumStorage/client/GuiBuilderQuantumStorage

### ISSUE THREAD

**Issue by sandalle** [gigabit101/QuantumStorage#84]
When running on a server, I get after updating Reborn Core from 1.11.2-2.16.0.112 to 1.11.2-2.16.1.114. A client runs just fine with the updated Reborn Core.

I updated Forge from 1.11.2-13.20.0.2309 to 1.11.2-13.20.0.2312, but tried reverting to 1.11.2-13.20.0.2309 and still couldn't load my world.

crash-report: [crash-2017-06-02_20.29.30-server.txt](https://github.com/gigabit101/QuantumStorage/files/1049357/crash-2017-06-02_20.29.30-server.txt)

**Comment by modmuss50** [comment]
That might have been me, I didn't expect gig to be using GUIs on the server. Revert the last Reborncore commit

**Comment by modmuss50** [comment]
Can you check to see if it works with the one version older of Reborncore?

**Comment by sandalle** [comment]
@modmuss50 yes, sorry I wasn't more clear. :) Quantum Storage 4.2.2 works fine with Reborn Core 1.11.2-2.16.0.112 and Forge 1.11.2-13.20.0.2309 or 1.11.2-13.20.0.2312 (I mentioned those as I first thought it was my upgrade to newer Forge which caused the problem). The error posted occurs when I update Reborn Core to 1.11.2-2.16.1.114 (no other changes). I reverted Reborn Core to 1.11.2-2.16.0.112 and kept my other updates (Forge and a few others) and this GUI error no longer occurs on my server.

**Comment by sandalle** [comment]
Should I move this issue to https://github.com/TechReborn/RebornCore/issues ?

**Comment by modmuss50** [comment]
No, I can quickly revert that change now

**Comment by modmuss50** [comment]
Ok, fixed. A few version will be on curse once its built and been approved.

**Comment by sandalle** [comment]
Thank you for the quick fix. :) I'll test it tomorrow (errr...it is tomorrow, so later today ;)).

**Comment by sandalle** [comment]
Reborn Core 1.11.2-2.16.1.115 fixed loading for me on the server, thank you @modmuss50 for the quick fix. :)
